Repository TravelCompass-UMC/Backend, pull requests merged in 2024-01, with the labels that each got.

#3 Feat: 프로젝트 초기화
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/travelcompass/api/TravelCompassWasApplication.java
  src/main/resources/application.yml
  src/test/java/com/travelcompass/api/TravelCompassWasApplicationTests.java
Labels: feature

#5 Feat: swagger 초기 설정
  .github/pull_request_template.md
  src/main/java/com/travelcompass/api/global/SwaggerConfig.java
Labels: feature

#8 [#6] CI/CD 파이프라인 구축
  .ebextensions_dev/00-makeFiles.config
  .ebextensions_dev/01-set-timezone.config
  .github/workflows/dev_deploy.yml
  .platform/nginx.conf
  Procfile
  build.gradle
  src/main/java/com/travelcompass/api/web/controller/RootController.java
Labels: feature, ci

#12 [#10] 응답 코드 구현, 예외 핸들링 구현
  src/main/java/com/travelcompass/api/global/api_payload/ApiResponse.java
  src/main/java/com/travelcompass/api/global/api_payload/BaseCode.java
  src/main/java/com/travelcompass/api/global/api_payload/ErrorCode.java
  src/main/java/com/travelcompass/api/global/api_payload/ReasonDto.java
  src/main/java/com/travelcompass/api/global/api_payload/SuccessCode.java
  src/main/java/com/travelcompass/api/global/config/SwaggerConfig.java
  src/main/java/com/travelcompass/api/global/exception/GeneralException.java
  src/main/java/com/travelcompass/api/global/exception/GlobalExceptionHandler.java
Labels: feature

#14 [#7] 네이버 소셜 로그인 기반 spring security & JWT 설정
  build.gradle
  src/main/java/com/travelcompass/api/global/config/PasswordEncoderConfig.java
  src/main/java/com/travelcompass/api/global/config/WebSecurityConfig.java
  src/main/java/com/travelcompass/api/global/entity/CustomUserDetails.java
  src/main/java/com/travelcompass/api/global/entity/UserEntity.java
  src/main/java/com/travelcompass/api/global/jwt/JwtRequestDto.java
  src/main/java/com/travelcompass/api/global/jwt/JwtTokenDto.java
  src/main/java/com/travelcompass/api/global/jwt/JwtTokenFilter.java
  src/main/java/com/travelcompass/api/global/jwt/JwtTokenUtils.java
  src/main/java/com/travelcompass/api/global/oauth/OAuth2SuccessHandler.java
  src/main/java/com/travelcompass/api/global/oauth/OAuth2UserServiceImpl.java
  src/main/java/com/travelcompass/api/global/repository/UserRepository.java
  src/main/java/com/travelcompass/api/global/service/JpaUserDetailsManager.java
  src/main/java/com/travelcompass/api/web/controller/TokenController.java
  src/main/java/com/travelcompass/api/web/controller/ViewController.java
  src/main/resources/application.yml
  src/main/resources/templates/login.html
Labels: feature

#13 [#11] Address 관련 작업 및 테스트 작성
  src/main/java/com/travelcompass/api/adress/domain/Address.java
  src/main/java/com/travelcompass/api/adress/repository/AddressRepository.java
  src/main/java/com/travelcompass/api/adress/service/AddressService.java
  src/main/java/com/travelcompass/api/global/api_payload/ErrorCode.java
  src/test/java/com/travelcompass/api/adress/AddressTest.java
  src/test/java/com/travelcompass/api/adress/domain/AddressDomainTest.java
  src/test/java/com/travelcompass/api/adress/repository/AddressRepositoryTest.java
  src/test/java/com/travelcompass/api/adress/service/AddressServiceTest.java
Labels: feature

#22 [#17] 지역, 장소 관련 기본 구현
  src/main/java/com/travelcompass/api/address/domain/Address.java
  src/main/java/com/travelcompass/api/address/repository/AddressRepository.java
  src/main/java/com/travelcompass/api/address/service/AddressService.java
  src/main/java/com/travelcompass/api/global/api_payload/ErrorCode.java
  src/main/java/com/travelcompass/api/global/controller/RootController.java
  src/main/java/com/travelcompass/api/global/controller/TokenController.java
  src/main/java/com/travelcompass/api/global/controller/ViewController.java
  src/main/java/com/travelcompass/api/global/entity/BaseEntity.java
  src/main/java/com/travelcompass/api/location/domain/Location.java
  src/main/java/com/travelcompass/api/location/domain/LocationType.java
  src/main/java/com/travelcompass/api/location/repository/LocationRepository.java
  src/main/java/com/travelcompass/api/location/service/LocationService.java
  src/main/java/com/travelcompass/api/region/domain/Region.java
  src/main/java/com/travelcompass/api/region/repository/RegionRepository.java
  src/main/java/com/travelcompass/api/region/service/RegionService.java
  src/main/resources/application.yml
  src/test/java/com/travelcompass/api/address/AddressTest.java
  src/test/java/com/travelcompass/api/address/domain/AddressDomainTest.java
  src/test/java/com/travelcompass/api/address/repository/AddressRepositoryTest.java
  src/test/java/com/travelcompass/api/address/service/AddressServiceTest.java
  src/test/java/com/travelcompass/api/region/RegionIntegrationTest.java
  src/test/java/com/travelcompass/api/region/domain/RegionTest.java
  src/test/java/com/travelcompass/api/region/service/RegionServiceTest.java
Labels: feature

#24 [#19] [Feature] 여행계획 관련 엔티티 구현 및 테스트
  src/main/java/com/travelcompass/api/plan/domain/Plan.java
  src/main/java/com/travelcompass/api/plan/domain/PlanGroup.java
  src/main/java/com/travelcompass/api/plan/domain/PlanLocation.java
  src/main/java/com/travelcompass/api/plan/domain/PlanVehicle.java
  src/main/java/com/travelcompass/api/plan/domain/ViewCount.java
  src/test/java/com/travelcompass/api/plan/domain/PlanDomainTest.java
Labels: feature

#30 [#25] S3 설정
  build.gradle
  src/main/java/com/travelcompass/api/global/config/AmazonConfig.java
  src/main/java/com/travelcompass/api/global/entity/Uuid.java
  src/main/java/com/travelcompass/api/global/repository/UuidRepository.java
  src/main/java/com/travelcompass/api/global/s3/AmazonS3Manager.java
Labels: feature

#32 [wip][#28] 여행 관련 서비스 구현
  src/main/java/com/travelcompass/api/global/api_payload/ErrorCode.java
  src/main/java/com/travelcompass/api/hashtag/Service/HashtagService.java
  src/main/java/com/travelcompass/api/hashtag/converter/HashtagConverter.java
  src/main/java/com/travelcompass/api/hashtag/repository/HashtagPlanRepository.java
  src/main/java/com/travelcompass/api/hashtag/repository/HashtagRepository.java
  src/main/java/com/travelcompass/api/oauth/service/UserService.java
  src/main/java/com/travelcompass/api/plan/converter/PlanConverter.java
  src/main/java/com/travelcompass/api/plan/domain/Plan.java
  src/main/java/com/travelcompass/api/plan/dto/PlanRequestDto.java
  src/main/java/com/travelcompass/api/plan/dto/PlanResponseDto.java
  src/main/java/com/travelcompass/api/plan/repository/PlanLocationRepository.java
  src/main/java/com/travelcompass/api/plan/repository/PlanRepository.java
  src/main/java/com/travelcompass/api/plan/repository/PlanUserRepository.java
  src/main/java/com/travelcompass/api/plan/repository/ViewCountRepository.java
  src/main/java/com/travelcompass/api/plan/service/PlanService.java
Labels: feature

#38 [#37] S3 관련 설정 버그 수정
  src/main/resources/application.yml
Labels: bug

#39 [#36] 주소를 좌표로 변환 기능 구현
  build.gradle
  src/main/java/com/travelcompass/api/address/service/AddressService.java
  src/main/java/com/travelcompass/api/address/service/Coordinates.java
  src/main/java/com/travelcompass/api/global/config/WebSecurityConfig.java
  src/main/resources/application.yml
Labels: feature

#41 [#35] 여행계획 관련 API 개발
  src/main/java/com/travelcompass/api/global/api_payload/ErrorCode.java
  src/main/java/com/travelcompass/api/global/api_payload/SuccessCode.java
  src/main/java/com/travelcompass/api/hashtag/converter/HashtagConverter.java
  src/main/java/com/travelcompass/api/hashtag/repository/HashtagRepository.java
  src/main/java/com/travelcompass/api/hashtag/service/HashtagService.java
  src/main/java/com/travelcompass/api/plan/controller/PlanController.java
  src/main/java/com/travelcompass/api/plan/converter/PlanConverter.java
  src/main/java/com/travelcompass/api/plan/domain/Plan.java
  src/main/java/com/travelcompass/api/plan/domain/PlanLocation.java
  src/main/java/com/travelcompass/api/plan/dto/PlanRequestDto.java
  src/main/java/com/travelcompass/api/plan/dto/PlanResponseDto.java
  src/main/java/com/travelcompass/api/plan/repository/PlanLikeRepository.java
  src/main/java/com/travelcompass/api/plan/repository/PlanLocationRepository.java
  src/main/java/com/travelcompass/api/plan/repository/PlanRepository.java
  src/main/java/com/travelcompass/api/plan/service/PlanService.java
  src/main/java/com/travelcompass/api/region/repository/RegionRepository.java
  src/main/java/com/travelcompass/api/region/service/RegionService.java
Labels: feature

#45 [#33] 여행계획 좋아요 기능 구현
  src/main/java/com/travelcompass/api/global/api_payload/SuccessCode.java
  src/main/java/com/travelcompass/api/oauth/domain/User.java
  src/main/java/com/travelcompass/api/plan/controller/PlanLikeController.java
  src/main/java/com/travelcompass/api/plan/domain/Plan.java
  src/main/java/com/travelcompass/api/plan/repository/PlanLikeRepository.java
  src/main/java/com/travelcompass/api/plan/service/PlanLikeService.java
Labels: feature

#47 [#40'''] /health 열기
  src/main/java/com/travelcompass/api/global/config/WebSecurityConfig.java
Labels: refactor

#48 [#44] Fix: plan API 실행중 버그 수정
  src/main/java/com/travelcompass/api/hashtag/service/HashtagService.java
  src/main/java/com/travelcompass/api/oauth/service/UserService.java
  src/main/java/com/travelcompass/api/plan/controller/PlanController.java
  src/main/java/com/travelcompass/api/plan/controller/PlanLikeController.java
  src/main/java/com/travelcompass/api/plan/dto/PlanRequestDto.java
  src/main/java/com/travelcompass/api/plan/service/PlanService.java
Labels: refactor
