Repository TravelCompass-UMC/Backend, pull requests merged in 2024-02, with the labels that each got.

#51 CI/CD 버그 수정
  build.gradle
  src/main/java/com/travelcompass/api/global/config/PasswordEncoderConfig.java
  src/main/java/com/travelcompass/api/global/config/WebSecurityConfig.java
  src/main/java/com/travelcompass/api/global/controller/UserController.java
  src/main/java/com/travelcompass/api/oauth/OAuth2SuccessHandler.java
  src/main/java/com/travelcompass/api/oauth/OAuth2UserServiceImpl.java
  src/main/java/com/travelcompass/api/oauth/jwt/CustomUserDetails.java
  src/main/java/com/travelcompass/api/oauth/jwt/JwtTokenFilter.java
  src/main/java/com/travelcompass/api/oauth/jwt/JwtTokenUtils.java
  src/main/java/com/travelcompass/api/oauth/jwt/RefreshToken.java
  src/main/java/com/travelcompass/api/oauth/service/JpaUserDetailsManager.java
  src/main/java/com/travelcompass/api/oauth/service/UserService.java
  src/main/java/com/travelcompass/api/plan/controller/PlanController.java
  src/main/java/com/travelcompass/api/plan/controller/PlanLikeController.java
Labels: bug, ci

#52 [#50] health-check시 직접적인 200 반환
  src/main/java/com/travelcompass/api/global/controller/RootController.java
Labels: bug, ci

#53 [#50] ci/cd 수정중
  src/main/java/com/travelcompass/api/global/config/AmazonConfig.java
  src/main/java/com/travelcompass/api/global/controller/RootController.java
  src/main/java/com/travelcompass/api/global/controller/UserController.java
  src/main/java/com/travelcompass/api/global/s3/AmazonS3Manager.java
  src/main/java/com/travelcompass/api/oauth/jwt/JwtTokenUtils.java
  src/main/java/com/travelcompass/api/oauth/service/UserService.java
  src/main/resources/application.yml
Labels: bug, ci

#55 [#51] 원상복구
  build.gradle
  src/main/java/com/travelcompass/api/global/config/AmazonConfig.java
  src/main/java/com/travelcompass/api/global/config/PasswordEncoderConfig.java
  src/main/java/com/travelcompass/api/global/config/WebSecurityConfig.java
  src/main/java/com/travelcompass/api/global/controller/UserController.java
  src/main/java/com/travelcompass/api/global/s3/AmazonS3Manager.java
  src/main/java/com/travelcompass/api/oauth/OAuth2SuccessHandler.java
  src/main/java/com/travelcompass/api/oauth/OAuth2UserServiceImpl.java
  src/main/java/com/travelcompass/api/oauth/domain/User.java
  src/main/java/com/travelcompass/api/oauth/jwt/CustomUserDetails.java
  src/main/java/com/travelcompass/api/oauth/jwt/JwtTokenFilter.java
  src/main/java/com/travelcompass/api/oauth/jwt/JwtTokenUtils.java
  src/main/java/com/travelcompass/api/oauth/jwt/RefreshToken.java
  src/main/java/com/travelcompass/api/oauth/service/JpaUserDetailsManager.java
  src/main/java/com/travelcompass/api/oauth/service/UserService.java
  src/main/java/com/travelcompass/api/plan/controller/PlanController.java
  src/main/java/com/travelcompass/api/plan/controller/PlanLikeController.java
  src/main/resources/application.yml
  src/test/java/com/travelcompass/api/address/domain/AddressDomainTest.java
Labels: refactor

#56 [#54] 장소 좋아요 기능 구현
  src/main/java/com/travelcompass/api/global/api_payload/SuccessCode.java
  src/main/java/com/travelcompass/api/location/controller/LocationLikeController.java
  src/main/java/com/travelcompass/api/location/domain/Location.java
  src/main/java/com/travelcompass/api/location/domain/LocationLike.java
  src/main/java/com/travelcompass/api/location/repository/LocationLikeRepository.java
  src/main/java/com/travelcompass/api/location/service/LocationLikeService.java
  src/main/java/com/travelcompass/api/oauth/domain/User.java
  src/main/resources/application.yml
Labels: feature

#57 [#50] 서버 포트 변경
  src/main/resources/application.yml
Labels: bug, ci

#58 [#50] ci/cd 제거 및 ec2 업로드로 변경
  .github/workflows/dev_deploy.yml
  src/main/resources/application.yml
Labels: refactor, ci

#59 [#50] 서버에서 에러 나는 테스트 주석 처리
  src/test/java/com/travelcompass/api/TravelCompassWasApplicationTests.java
  src/test/java/com/travelcompass/api/address/AddressTest.java
  src/test/java/com/travelcompass/api/address/repository/AddressRepositoryTest.java
  src/test/java/com/travelcompass/api/region/RegionIntegrationTest.java
Labels: bug

#60 [#21] 마이페이지 관련 API 개발
  src/main/java/com/travelcompass/api/address/domain/Address.java
  src/main/java/com/travelcompass/api/global/api_payload/ErrorCode.java
  src/main/java/com/travelcompass/api/global/api_payload/SuccessCode.java
  src/main/java/com/travelcompass/api/mypage/controller/MypageController.java
  src/main/java/com/travelcompass/api/mypage/converter/MypageConverter.java
  src/main/java/com/travelcompass/api/mypage/dto/MypageResponseDto.java
  src/main/java/com/travelcompass/api/mypage/service/MypageService.java
  src/main/java/com/travelcompass/api/oauth/domain/User.java
Labels: feature

#67 [#63] 로그아웃 로직 수정 + refresh token db 저장
  src/main/java/com/travelcompass/api/global/api_payload/SuccessCode.java
  src/main/java/com/travelcompass/api/global/config/WebSecurityConfig.java
  src/main/java/com/travelcompass/api/oauth/OAuth2SuccessHandler.java
  src/main/java/com/travelcompass/api/oauth/controller/TokenController.java
  src/main/java/com/travelcompass/api/oauth/controller/UserController.java
  src/main/java/com/travelcompass/api/oauth/jwt/AuthCreationFilter.java
  src/main/java/com/travelcompass/api/oauth/jwt/JwtTokenUtils.java
  src/main/java/com/travelcompass/api/oauth/jwt/JwtValidationFilter.java
  src/main/java/com/travelcompass/api/oauth/jwt/RefreshToken.java
  src/main/java/com/travelcompass/api/oauth/repository/RefreshTokenRepository.java
  src/main/java/com/travelcompass/api/oauth/service/UserService.java
  src/main/resources/application.yml
Labels: refactor, feature

#70 [#69] 마이페이지 에러부분 주석처리
  src/main/java/com/travelcompass/api/mypage/converter/MypageConverter.java
  src/main/java/com/travelcompass/api/mypage/service/MypageService.java
Labels: bug

#71 [#66] 장소 관련 api 구현
  src/main/java/com/travelcompass/api/LocalDataLoader.java
  src/main/java/com/travelcompass/api/TempDataLoader.java
  src/main/java/com/travelcompass/api/location/controller/LocationController.java
  src/main/java/com/travelcompass/api/location/controller/LocationLikeController.java
  src/main/java/com/travelcompass/api/location/converter/BusinessHoursConverter.java
  src/main/java/com/travelcompass/api/location/converter/LocationConverter.java
  src/main/java/com/travelcompass/api/location/domain/Location.java
  src/main/java/com/travelcompass/api/location/dto/BusinessHoursDto.java
  src/main/java/com/travelcompass/api/location/dto/LocationRequestDto.java
  src/main/java/com/travelcompass/api/location/dto/LocationResponseDto.java
  src/main/java/com/travelcompass/api/location/dto/LocationScrapingDto.java
  src/main/java/com/travelcompass/api/location/repository/BusinessHoursRepository.java
  src/main/java/com/travelcompass/api/location/repository/LocationImageRepository.java
  src/main/java/com/travelcompass/api/location/repository/LocationInfoRepository.java
  src/main/java/com/travelcompass/api/location/repository/LocationLikeRepository.java
  src/main/java/com/travelcompass/api/location/repository/LocationRepository.java
  src/main/java/com/travelcompass/api/location/service/BusinessHoursService.java
  src/main/java/com/travelcompass/api/location/service/LocationImageService.java
  src/main/java/com/travelcompass/api/location/service/LocationInfoService.java
  src/main/java/com/travelcompass/api/location/service/LocationLikeService.java
  src/main/java/com/travelcompass/api/location/service/LocationScraper.java
  src/main/java/com/travelcompass/api/location/service/LocationService.java
  src/main/java/com/travelcompass/api/mypage/converter/MypageConverter.java
  src/main/java/com/travelcompass/api/mypage/service/MypageService.java
  src/main/java/com/travelcompass/api/oauth/OAuth2SuccessHandler.java
  src/main/java/com/travelcompass/api/plan/service/PlanService.java
  src/main/resources/application.yml
Labels: feature

#72 [#64] 마이페이지 스웨거 설정 및 장소 검색 수정
  src/main/java/com/travelcompass/api/location/domain/Location.java
  src/main/java/com/travelcompass/api/mypage/controller/MypageController.java
  src/main/java/com/travelcompass/api/mypage/converter/MypageConverter.java
  src/main/java/com/travelcompass/api/mypage/dto/MypageResponseDto.java
  src/main/java/com/travelcompass/api/mypage/service/MypageService.java
Labels: refactor

#80 [#79] swagger에 담당자 추가 - 최재영
  src/main/java/com/travelcompass/api/location/controller/LocationController.java
  src/main/java/com/travelcompass/api/region/controller/RegionController.java
Labels: refactor

#82 [#20] 네이버 경로 api
  src/main/java/com/travelcompass/api/LocalDataLoader.java
  src/main/java/com/travelcompass/api/feign/Naver/NaverDurationClient.java
  src/main/java/com/travelcompass/api/feign/Naver/NaverPathController.java
  src/main/java/com/travelcompass/api/feign/Naver/NaverPathService.java
  src/main/java/com/travelcompass/api/global/api_payload/SuccessCode.java
  src/main/java/com/travelcompass/api/global/config/WebSecurityConfig.java
  src/main/java/com/travelcompass/api/oauth/jwt/JwtValidationFilter.java
  src/main/resources/application.yml
Labels: feature

#86 [#85] CORS 설정
  src/main/java/com/travelcompass/api/global/config/WebSecurityConfig.java
Labels: refactor

#87 [#20] 대중교통 경로 api 연결
  src/main/java/com/travelcompass/api/feign/ODsay/ODsayController.java
  src/main/java/com/travelcompass/api/feign/ODsay/ODsayDurationClient.java
  src/main/java/com/travelcompass/api/feign/ODsay/ODsayService.java
  src/main/java/com/travelcompass/api/global/api_payload/ErrorCode.java
  src/main/java/com/travelcompass/api/global/api_payload/SuccessCode.java
  src/main/resources/application.yml
Labels: feature
